environment:
  matrix:
    - julia_version: 0.7
    - julia_version: 1
    - julia_version: nightly

platform:
  - x86
  - x64

matrix:
  allow_failures:
    - julia_version: nightly # Allow nightly to fail

branches:
  only:
    - master
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

build_script:
# Need to convert from shallow to complete for Pkg.clone to work
  - IF EXIST .git\shallow (git fetch --unshallow)
  - C:\projects\julia\bin\julia -e "versioninfo();
      Pkg.clone(pwd(), \"ProgressBars\"); Pkg.build(\"ProgressBars\")"

test_script:
  - C:\projects\julia\bin\julia -e "Pkg.test(\"ProgressBars\")"
